const programsData = [
    {
        id: "undergraduate",
        title: "Undergraduate",
        subtitle: "Select Your Path",
        theme: "red",
        layout: "static-left",
        icon: "sparkles",
        linkto: "#",
        staticList: [
            { name: "B.B.A. BUSINESS ADMINISTRATION", link: "#" },
            { name: "B.C.A. COMPUTER APPLICATIONS", link: "#" },
            { name: "B.COM ACCOUNTING & FINANCE", link: "#" },
            { name: "B.COM BANK MANAGEMENT", link: "#" },
            { name: "B.COM COMPUTER APPLICATION", link: "#" },
            { name: "B.COM CORPORATE SECRETARYSHIP", link: "#" },
            { name: "B.COM GENERAL", link: "#" },
            { name: "B.SC BIOTECHNOLOGY", link: "#" },
            { name: "B.SC COMPUTER SCIENCE", link: "#" },
            { name: "B.SC CS [ ARTIFICIAL INTELLIGENCE ]", link: "#" },
            { name: "B.SC CS [ DATA SCIENCE ]", link: "#" },
            { name: "B.SC MICROBIOLOGY", link: "#" },
            { name: "B.SC PSYCHOLOGY", link: "#" },
            { name: "B.SC VISUAL COMMUNICATION", link: "#" },
            { name: "B.S.W SOCIAL WORK", link: "#" },
        ],
        sliderItems: [
            { name: "B.B.A. Business Administration", color: "blue", link: "#" },
            { name: "B.C.A. Computer Applications", color: "green", link: "#" },
            { name: "B.Com Bank Management", color: "blue", link: "#" },
            { name: "B.Com Corporate Secretaryship", color: "green", link: "#" },
            { name: "B.Sc Artificial Intelligence", color: "blue", link: "#" },
            { name: "B.Sc Biotechnology", color: "green", link: "#" },
            { name: "B.Sc Computer Science", color: "blue", link: "#" },
            { name: "B.Sc Data Science", color: "green", link: "#" },
            { name: "B.Sc Microbiology", color: "blue", link: "#" },
            { name: "B.Sc Psychology", color: "green", link: "#" },
            { name: "B.Sc Visual Communication", color: "blue", link: "#" },
        ],
    },
    {
        id: "postgraduate",
        title: "Post Graduate",
        subtitle: "Master Your Skills",
        theme: "blue",
        layout: "static-right",
        icon: "sparkles",
        bgImage: "images/pg-text.png",
        linkto: "#",
        staticList: [
            { name: "MBA", link: "#" },
            { name: "MCA", link: "#" },
            { name: "M.COM GENERAL", link: "#" },
            { name: "M.SC APPLIED MICROBIOLOGY", link: "#" },
            { name: "M.SC BIOTECHNOLOGY", link: "#" },
            { name: "M.SC COMPUTER SCIENCE", link: "#" },
            { name: "M.SC INFORMATION TECHNOLOGY", link: "#" },
            { name: "M.SC VISUAL COMMUNICATION", link: "#" },
            { name: "M.S.W SOCIAL WORK", link: "#" },
        ],
        sliderItems: [
            { name: "MBA", color: "green", link: "#" },
            { name: "MCA", color: "blue", link: "#" },
            { name: "M.Com General", color: "green", link: "#" },
            { name: "M.Sc Applied Microbiology", color: "blue", link: "#" },
            { name: "M.Sc Biotechnology", color: "green", link: "#" },
            { name: "M.Sc Computer Science", color: "blue", link: "#" },
            { name: "M.Sc Information Technology", color: "green", link: "#" },
            { name: "M.Sc Visual Communication", color: "blue", link: "#" },
            { name: "M.S.W Social Work", color: "green", link: "#" },
        ],
    },
    {
        id: "research",
        title: "Research",
        subtitle: "Doctoral Programmes",
        theme: "blue",
        layout: "static-left",
        icon: "scroll",
        bgImage: "./images/sclor.jpg",
        linkto: "#",
        staticList: [
            { name: "PH.D BIOTECHNOLOGY", link: "#" },
            { name: "PH.D COMMERCE", link: "#" },
            { name: "PH.D MICROBIOLOGY", link: "#" },
        ],
        sliderItems: [
            { name: "Ph.D Biotechnology", color: "blue", link: "#" },
            { name: "Ph.D Commerce", color: "green", link: "#" },
            { name: "Ph.D Microbiology", color: "blue", link: "#" },
        ],
    },
    {
        id: "diploma",
        title: "Diploma",
        subtitle: "Vocational Training",
        theme: "red",
        layout: "static-right",
        icon: "book-open",
        bgImage: "images/pg-text.png",
        linkto: "#",
        staticList: [
            { name: "VOCATIONAL DIPLOMA IN COMPUTER HARDWARE SERVICING (VDHS)", link: "#" },
            { name: "VOCATIONAL DIPLOMA IN COMPUTER APPLICATIONS (VDCA)", link: "#" },
            { name: "VOCATIONAL DIPLOMA IN BEAUTICIAN (VDIB)", link: "#" },
            { name: "VOCATIONAL DIPLOMA IN DESKTOP PUBLISHING (VDTP)", link: "#" },
            { name: "VOCATIONAL DIPLOMA IN GENERAL DUTY ASSISTANT (VDGA)", link: "#" },
            { name: "DIPLOMA IN OPTOMETRY", link: "#" },
            { name: "DIPLOMA IN MEDICAL LABORATORY TECHNOLOGY", link: "#" },
        ],
        sliderItems: [
            { name: "Hardware Servicing (VDHS)", color: "blue", link: "#" },
            { name: "Computer Applications (VDCA)", color: "green", link: "#" },
            { name: "Beautician (VDIB)", color: "blue", link: "#" },
            { name: "Desktop Publishing (VDTP)", color: "green", link: "#" },
            { name: "General Duty Assistant (VDGA)", color: "blue", link: "#" },
            { name: "Diploma in Optometry", color: "green", link: "#" },
            { name: "Medical Lab Technology", color: "blue", link: "#" },
        ],
    },
];
